_prefs: 
  mapid: tesera.aa34f228
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: Avalanche Canada and Tesera Systems Inc.
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -126.4087
  - 53.1929
  - 6
description: The overlay features, labels, regions, etc.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: ac-overlay-styles
source: "mapbox:///tesera.0097b017"
styles: 
  - style.mss
template: ''
